const assert = require('assert');
const assets = require('../src/data/asset-manifest.js');

assert.ok(assets.assetSourceGuidelines.preferredSources.includes('Itch.io'));
assert.ok(assets.assetSourceGuidelines.preferredSources.includes('OpenGameArt.org'));
assert.ok(assets.assetSourceGuidelines.preferredSearches.includes('Top down Tank Sprite'));
assert.strictEqual(assets.assetSourceGuidelines.requiredLicenseNoteFolder, 'assets/licenses/');
assert.strictEqual(assets.plannedAssetFolders.tankSprites, 'assets/sprites/tanks/');
assert.strictEqual(assets.plannedAssetFolders.effectSprites, 'assets/sprites/effects/');
assert.strictEqual(assets.plannedAssetFolders.rankSprites, 'assets/sprites/ranks/');
assert.strictEqual(assets.plannedAssetFolders.licenses, 'assets/licenses/');
assert.ok(Object.prototype.hasOwnProperty.call(assets.spriteActorSchema, 'hullTexture'));
assert.ok(Object.prototype.hasOwnProperty.call(assets.spriteActorSchema, 'turretTexture'));
assert.ok(Object.prototype.hasOwnProperty.call(assets.spriteActorSchema, 'fallbackSvg'));
assert.strictEqual(assets.importedSpriteTrials.length, 17);
assert.strictEqual(assets.importedSpriteTrials[0].license.includes('CC0'), true);
assert.strictEqual(assets.importedSpriteTrials[0].hullTexture, 'kenney:playerHull');
assert.strictEqual(assets.importedSpriteTrials[1].turretTexture, 'kenney:enemyTurret');
assert.strictEqual(assets.importedSpriteTrials[2].texture, 'bossTankDismantler');
assert.strictEqual(assets.importedSpriteTrials[2].spritesheetPath, 'assets/sprites/enemies/tank-dismantler-spritesheet.png');
assert.deepStrictEqual(assets.importedSpriteTrials[2].walkFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[2].attackFrames, [6, 7, 8, 9, 10, 11]);
assert.strictEqual(assets.importedSpriteTrials[3].texture, 'playerTankBattle');
assert.strictEqual(assets.importedSpriteTrials[3].spritesheetPath, 'assets/sprites/tanks/player-tank-spritesheet.png');
assert.deepStrictEqual(assets.importedSpriteTrials[3].idleFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].heavyFireFrames, [12, 13, 14, 15, 16, 17]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].hitFrames, [18, 19, 20, 21, 22, 23]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].weakFrames, [18, 19, 20, 21, 22, 23]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].destroyedFrames, [24, 25, 26, 27, 28, 29]);
const byTexture = Object.fromEntries(assets.importedSpriteTrials.map((entry) => [entry.texture, entry]));
assert.strictEqual(byTexture.playerTankCromwellBattle.spritesheetPath, 'assets/sprites/tanks/cromwell-player-tank-spritesheet.png');
assert.deepStrictEqual(byTexture.playerTankCromwellBattle.idleFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(byTexture.playerTankCromwellBattle.destroyedFrames, [24, 25, 26, 27, 28, 29]);
assert.strictEqual(byTexture.playerTankIs2Battle.spritesheetPath, 'assets/sprites/tanks/is2-player-tank-spritesheet.png');
assert.deepStrictEqual(byTexture.playerTankIs2Battle.idleFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(byTexture.playerTankIs2Battle.destroyedFrames, [24, 25, 26, 27, 28, 29]);
assert.strictEqual(byTexture.arcaneSparkShell.spritesheetPath, 'assets/sprites/effects/arcane-spark-shell-spritesheet.png');
assert.strictEqual(byTexture.arcaneSparkShell.frameWidth, 256);
assert.strictEqual(byTexture.arcaneSparkShell.frameHeight, 160);
assert.deepStrictEqual(byTexture.arcaneSparkShell.effectFrames, [0, 1, 2, 3]);
assert.strictEqual(byTexture.regularInfantry.spritesheetPath, 'assets/sprites/enemies/regular-infantry-spritesheet.png');
assert.strictEqual(byTexture.regularInfantry.frameWidth, 469);
assert.strictEqual(byTexture.regularInfantry.frameHeight, 300);
assert.deepStrictEqual(byTexture.regularInfantry.walkFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(byTexture.regularInfantry.fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(byTexture.regularInfantry.hitFrames, [18, 19, 20, 21, 22, 23]);
assert.strictEqual(byTexture.regularEnemyTank.spritesheetPath, 'assets/sprites/enemies/regular-enemy-tank-spritesheet.png');
assert.strictEqual(byTexture.regularEnemyTank.frameWidth, 469);
assert.strictEqual(byTexture.regularEnemyTank.frameHeight, 300);
assert.deepStrictEqual(byTexture.regularEnemyTank.idleFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(byTexture.regularEnemyTank.fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(byTexture.regularEnemyTank.hitFrames, [18, 19, 20, 21, 22, 23]);
assert.strictEqual(byTexture.grenadier.spritesheetPath, 'assets/sprites/enemies/grenadier-spritesheet.png');
assert.strictEqual(byTexture.grenadier.frameWidth, 469);
assert.strictEqual(byTexture.grenadier.frameHeight, 300);
assert.deepStrictEqual(byTexture.grenadier.walkFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(byTexture.grenadier.fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(byTexture.grenadier.hitFrames, [18, 19, 20, 21, 22, 23]);
assert.strictEqual(byTexture.burnedTrees.spritesheetPath, 'assets/sprites/environment/burned-trees-spritesheet.png');
assert.strictEqual(byTexture.burnedTrees.frameWidth, 704);
assert.strictEqual(byTexture.burnedTrees.frameHeight, 1536);
assert.deepStrictEqual(byTexture.burnedTrees.propFrames, [0, 1, 2, 3]);
assert.strictEqual(byTexture.ruinedHouses.frameWidth, 938);
assert.strictEqual(byTexture.ruinedHouses.frameHeight, 768);
assert.strictEqual(byTexture.trenchStrips.frameWidth, 2816);
assert.strictEqual(byTexture.trenchStrips.frameHeight, 512);
assert.deepStrictEqual(byTexture.craterTracks.propFrames, [0, 1, 2, 3, 4, 5]);
assert.strictEqual(byTexture.forestClusters.frameWidth, 1408);
assert.strictEqual(byTexture.forestClusters.frameHeight, 768);
assert.strictEqual(byTexture['css:battlefield-background'].imagePath, 'assets/sprites/environment/battlefield-background.png');
assert.strictEqual(byTexture['css:battlefield-background'].width, 2752);
assert.strictEqual(byTexture['css:battlefield-background'].height, 1536);
assert.strictEqual(byTexture['css:mastery-rank-icons'].spritesheetPath, 'assets/sprites/ranks/rank-icons.png');
assert.strictEqual(byTexture['css:mastery-rank-icons'].imagePaths.length, 11);
assert.strictEqual(byTexture['css:mastery-rank-icons'].imagePaths[0], 'assets/sprites/ranks/recruit.png');
assert.strictEqual(byTexture['css:mastery-rank-icons'].imagePaths[10], 'assets/sprites/ranks/colonel.png');

console.log('asset manifest tests passed');
