const assert = require('assert');
const assets = require('../src/data/asset-manifest.js');

assert.ok(assets.assetSourceGuidelines.preferredSources.includes('Itch.io'));
assert.ok(assets.assetSourceGuidelines.preferredSources.includes('OpenGameArt.org'));
assert.ok(assets.assetSourceGuidelines.preferredSearches.includes('Top down Tank Sprite'));
assert.strictEqual(assets.assetSourceGuidelines.requiredLicenseNoteFolder, 'assets/licenses/');
assert.strictEqual(assets.plannedAssetFolders.tankSprites, 'assets/sprites/tanks/');
assert.strictEqual(assets.plannedAssetFolders.effectSprites, 'assets/sprites/effects/');
assert.strictEqual(assets.plannedAssetFolders.rankSprites, 'assets/sprites/ranks/');
assert.strictEqual(assets.plannedAssetFolders.licenses, 'assets/licenses/');
assert.ok(Object.prototype.hasOwnProperty.call(assets.spriteActorSchema, 'hullTexture'));
assert.ok(Object.prototype.hasOwnProperty.call(assets.spriteActorSchema, 'turretTexture'));
assert.ok(Object.prototype.hasOwnProperty.call(assets.spriteActorSchema, 'fallbackSvg'));
assert.strictEqual(assets.importedSpriteTrials.length, 14);
assert.strictEqual(assets.importedSpriteTrials[0].license.includes('CC0'), true);
assert.strictEqual(assets.importedSpriteTrials[0].hullTexture, 'kenney:playerHull');
assert.strictEqual(assets.importedSpriteTrials[1].turretTexture, 'kenney:enemyTurret');
assert.strictEqual(assets.importedSpriteTrials[2].texture, 'bossTankDismantler');
assert.strictEqual(assets.importedSpriteTrials[2].spritesheetPath, 'assets/sprites/enemies/tank-dismantler-spritesheet.png');
assert.deepStrictEqual(assets.importedSpriteTrials[2].walkFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[2].attackFrames, [6, 7, 8, 9, 10, 11]);
assert.strictEqual(assets.importedSpriteTrials[3].texture, 'playerTankBattle');
assert.strictEqual(assets.importedSpriteTrials[3].spritesheetPath, 'assets/sprites/tanks/player-tank-spritesheet.png');
assert.deepStrictEqual(assets.importedSpriteTrials[3].idleFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].heavyFireFrames, [12, 13, 14, 15, 16, 17]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].hitFrames, [18, 19, 20, 21, 22, 23]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].weakFrames, [18, 19, 20, 21, 22, 23]);
assert.deepStrictEqual(assets.importedSpriteTrials[3].destroyedFrames, [24, 25, 26, 27, 28, 29]);
assert.strictEqual(assets.importedSpriteTrials[4].texture, 'regularInfantry');
assert.strictEqual(assets.importedSpriteTrials[4].spritesheetPath, 'assets/sprites/enemies/regular-infantry-spritesheet.png');
assert.strictEqual(assets.importedSpriteTrials[4].frameWidth, 469);
assert.strictEqual(assets.importedSpriteTrials[4].frameHeight, 300);
assert.deepStrictEqual(assets.importedSpriteTrials[4].walkFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[4].fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(assets.importedSpriteTrials[4].hitFrames, [18, 19, 20, 21, 22, 23]);
assert.strictEqual(assets.importedSpriteTrials[5].texture, 'regularEnemyTank');
assert.strictEqual(assets.importedSpriteTrials[5].spritesheetPath, 'assets/sprites/enemies/regular-enemy-tank-spritesheet.png');
assert.strictEqual(assets.importedSpriteTrials[5].frameWidth, 469);
assert.strictEqual(assets.importedSpriteTrials[5].frameHeight, 300);
assert.deepStrictEqual(assets.importedSpriteTrials[5].idleFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[5].fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(assets.importedSpriteTrials[5].hitFrames, [18, 19, 20, 21, 22, 23]);
assert.strictEqual(assets.importedSpriteTrials[6].texture, 'grenadier');
assert.strictEqual(assets.importedSpriteTrials[6].spritesheetPath, 'assets/sprites/enemies/grenadier-spritesheet.png');
assert.strictEqual(assets.importedSpriteTrials[6].frameWidth, 469);
assert.strictEqual(assets.importedSpriteTrials[6].frameHeight, 300);
assert.deepStrictEqual(assets.importedSpriteTrials[6].walkFrames, [0, 1, 2, 3, 4, 5]);
assert.deepStrictEqual(assets.importedSpriteTrials[6].fireFrames, [6, 7, 8, 9, 10, 11]);
assert.deepStrictEqual(assets.importedSpriteTrials[6].hitFrames, [18, 19, 20, 21, 22, 23]);
assert.strictEqual(assets.importedSpriteTrials[7].texture, 'burnedTrees');
assert.strictEqual(assets.importedSpriteTrials[7].spritesheetPath, 'assets/sprites/environment/burned-trees-spritesheet.png');
assert.strictEqual(assets.importedSpriteTrials[7].frameWidth, 704);
assert.strictEqual(assets.importedSpriteTrials[7].frameHeight, 1536);
assert.deepStrictEqual(assets.importedSpriteTrials[7].propFrames, [0, 1, 2, 3]);
assert.strictEqual(assets.importedSpriteTrials[8].texture, 'ruinedHouses');
assert.strictEqual(assets.importedSpriteTrials[8].frameWidth, 938);
assert.strictEqual(assets.importedSpriteTrials[8].frameHeight, 768);
assert.strictEqual(assets.importedSpriteTrials[9].texture, 'trenchStrips');
assert.strictEqual(assets.importedSpriteTrials[9].frameWidth, 2816);
assert.strictEqual(assets.importedSpriteTrials[9].frameHeight, 512);
assert.strictEqual(assets.importedSpriteTrials[10].texture, 'craterTracks');
assert.deepStrictEqual(assets.importedSpriteTrials[10].propFrames, [0, 1, 2, 3, 4, 5]);
assert.strictEqual(assets.importedSpriteTrials[11].texture, 'forestClusters');
assert.strictEqual(assets.importedSpriteTrials[11].frameWidth, 1408);
assert.strictEqual(assets.importedSpriteTrials[11].frameHeight, 768);
assert.strictEqual(assets.importedSpriteTrials[12].texture, 'css:battlefield-background');
assert.strictEqual(assets.importedSpriteTrials[12].imagePath, 'assets/sprites/environment/battlefield-background.png');
assert.strictEqual(assets.importedSpriteTrials[12].width, 2752);
assert.strictEqual(assets.importedSpriteTrials[12].height, 1536);
assert.strictEqual(assets.importedSpriteTrials[13].texture, 'css:mastery-rank-icons');
assert.strictEqual(assets.importedSpriteTrials[13].spritesheetPath, 'assets/sprites/ranks/rank-icons.png');
assert.strictEqual(assets.importedSpriteTrials[13].imagePaths.length, 11);
assert.strictEqual(assets.importedSpriteTrials[13].imagePaths[0], 'assets/sprites/ranks/recruit.png');
assert.strictEqual(assets.importedSpriteTrials[13].imagePaths[10], 'assets/sprites/ranks/colonel.png');

console.log('asset manifest tests passed');
