const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');

function bodyOf(functionName) {
  const start = source.indexOf(`function ${functionName}`);
  assert.notStrictEqual(start, -1, `Missing function ${functionName}`);
  const parametersEnd = source.indexOf(') {', start);
  assert.notStrictEqual(parametersEnd, -1, `Could not find body start for function ${functionName}`);
  const braceStart = source.indexOf('{', parametersEnd);
  let depth = 0;
  for (let index = braceStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    if (depth === 0) return source.slice(braceStart + 1, index);
  }
  throw new Error(`Could not parse function ${functionName}`);
}

const cameraKick = bodyOf('kickPhaserCamera');
assert.match(cameraKick, /camera\.shake\(/, 'Phaser camera shake should be used for impact feedback.');
assert.match(cameraKick, /camera\.flash\(/, 'Phaser camera flash should be used for explosion feedback.');

const shockwave = bodyOf('addPhaserShockwave');
assert.match(shockwave, /setStrokeStyle/, 'Explosion shockwave should be a stroked Phaser ring.');
assert.match(shockwave, /scale: heavy \? 6\.2 : 4\.2/, 'Shockwave should expand dramatically.');

const smoke = bodyOf('addPhaserSmoke');
assert.match(smoke, /puffCount = heavy \? 13 : 8/, 'Explosion should create multiple smoke puffs.');
assert.match(smoke, /scene\.add\.circle/, 'Smoke should be generated by Phaser primitives.');

const sparks = bodyOf('addPhaserSparks');
assert.match(sparks, /sparkCount = heavy \? 34 : 18/, 'Explosion should create many sparks.');
assert.match(sparks, /scene\.add\.rectangle/, 'Sparks should use Phaser primitives.');

const explosion = bodyOf('playPhaserExplosion');
assert.match(explosion, /kickPhaserCamera\(heavy \? "heavy" : "normal"\)/, 'Explosion should kick the Phaser camera.');
assert.match(explosion, /addPhaserShockwave\(/, 'Explosion should include shockwave.');
assert.match(explosion, /addPhaserSparks\(/, 'Explosion should include sparks.');
assert.match(explosion, /addPhaserSmoke\(/, 'Explosion should include smoke.');
assert.doesNotMatch(explosion, /const smoke = scene\.add\.circle/, 'Explosion should not regress to a single smoke circle.');

const debris = bodyOf('addPhaserArmorDebris');
assert.match(debris, /chunkCount = heavy \? 42 : 26/, 'Tank destruction should create many armor chunks.');
assert.match(debris, /scene\.add\.rectangle/, 'Tank destruction should use Phaser debris primitives.');

const destruction = bodyOf('playPhaserDestruction');
assert.match(destruction, /targetEl\.classList\.add\("fragmented"\)/, 'Tank body should fade out when Phaser destruction starts.');
assert.match(destruction, /addPhaserArmorDebris\(/, 'Tank destruction should throw armor debris.');
assert.match(destruction, /addPhaserSparks\(/, 'Tank destruction should include sparks.');
assert.match(destruction, /addPhaserSmoke\(/, 'Tank destruction should include smoke.');

const muzzleFlash = bodyOf('addPhaserMuzzleFlash');
assert.match(muzzleFlash, /scene\.add\.star/, 'Projectile fire should use a Phaser muzzle flash star.');
assert.match(muzzleFlash, /scene\.add\.circle/, 'Projectile fire should use a Phaser muzzle bloom.');

const projectileTrail = bodyOf('addPhaserProjectileTrail');
assert.match(projectileTrail, /trailCount = 8/, 'Projectile should leave multiple Phaser trail puffs.');
assert.match(projectileTrail, /scene\.add\.circle/, 'Projectile trail should use Phaser primitives.');

const impactGlint = bodyOf('addPhaserImpactGlint');
assert.match(impactGlint, /setStrokeStyle/, 'Projectile impact should create a stroked Phaser glint.');

const targetingLine = bodyOf('playPhaserTargetingLine');
assert.match(targetingLine, /phaserEffects\.add\.line/, 'Enemy attacks should use a Phaser targeting line.');
assert.match(targetingLine, /setLineWidth/, 'Targeting line should have visible thickness.');
assert.match(targetingLine, /phaserEffects\.add\.circle/, 'Targeting should include a Phaser impact reticle.');

const projectile = bodyOf('playPhaserProjectile');
assert.match(projectile, /addPhaserMuzzleFlash\(/, 'Projectile should trigger muzzle flash.');
assert.match(projectile, /addPhaserProjectileTrail\(/, 'Projectile should trigger trail effects.');
assert.match(projectile, /addPhaserImpactGlint\(/, 'Projectile should trigger impact glint.');
assert.match(projectile, /options\.onImpact\?\.\(\)/, 'Projectile impact callbacks should run only after the projectile reaches the target.');

assert.match(projectile, /options\.effectSheet === "arcaneSparkShell"/, 'Arcane Spark Shell should use its projectile spritesheet path.');
assert.match(projectile, /addPhaserArcaneSpark\(/, 'Arcane Spark Shell should render as a Phaser spritesheet projectile.');

const arcaneProjectile = bodyOf('addPhaserArcaneSpark');
assert.match(arcaneProjectile, /scene\.add\.sprite\(start\.x, start\.y, "arcaneSparkShell", 0\)/, 'Arcane projectile should be created from the spritesheet.');
assert.match(arcaneProjectile, /sprite\.play\("arcane-spark-shell-fire", true\)/, 'Arcane projectile should animate while flying.');
assert.match(arcaneProjectile, /setDisplaySize\(260, 162\)/, 'Arcane projectile should be large enough to notice in flight.');
assert.match(arcaneProjectile, /addPhaserArcaneImpact\(/, 'Arcane projectile should trigger a dedicated oversized impact effect.');

const arcaneImpact = bodyOf('addPhaserArcaneImpact');
assert.match(arcaneImpact, /setDisplaySize\(460, 288\)/, 'Arcane impact should use an oversized explosion sheet frame.');
assert.match(arcaneImpact, /scene\.add\.rectangle/, 'Arcane impact should include a visible magic pillar.');

const fire = bodyOf('fire');
assert.match(fire, /duration: projectileDuration,[\s\S]*onImpact: explodeOnImpact/, 'Player shell explosions should be tied to projectile impact completion.');
assert.doesNotMatch(fire, /setTimeout\(\(\) => \{[\s\S]*playPhaserExplosion\(enemyTank/, 'Player shell explosions should not use a fixed early timeout.');

const initPhaserEffects = bodyOf('initPhaserEffects');
assert.match(initPhaserEffects, /this\.load\.image\("kenney:playerHull"/, 'Phaser should preload Kenney player hull PNG.');
assert.match(initPhaserEffects, /this\.load\.image\("kenney:playerTurret"/, 'Phaser should preload Kenney player turret PNG.');
assert.match(initPhaserEffects, /this\.load\.image\("kenney:enemyHull"/, 'Phaser should preload Kenney enemy hull PNG.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("playerTankBattle"/, 'Phaser should preload the player tank battle spritesheet.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("playerTankIs2Battle"/, 'Phaser should preload the IS-2 player tank battle spritesheet.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("playerTankCromwellBattle"/, 'Phaser should preload the Cromwell player tank battle spritesheet.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("arcaneSparkShell"/, 'Phaser should preload the Arcane Spark Shell effect spritesheet.');
assert.match(initPhaserEffects, /frameWidth: 224[\s\S]*frameHeight: 144/, 'Player tank spritesheet should use fixed frame dimensions.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("bossTankDismantler"/, 'Phaser should preload the Tank Dismantler boss spritesheet.');
assert.match(initPhaserEffects, /frameWidth: 224/, 'Tank Dismantler spritesheet should use fixed frame width.');
assert.match(initPhaserEffects, /frameHeight: 224/, 'Tank Dismantler spritesheet should use fixed frame height.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("regularInfantry"/, 'Phaser should preload the regular soldier spritesheet.');
assert.match(initPhaserEffects, /frameWidth: 469[\s\S]*frameHeight: 300/, 'Regular soldier spritesheet should use fixed frame dimensions.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("regularEnemyTank"/, 'Phaser should preload the regular enemy tank spritesheet.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("grenadier"/, 'Phaser should preload the grenadier spritesheet.');
assert.match(initPhaserEffects, /phaserPlayerSprite = this\.add\.sprite/, 'Player actor should be a Phaser sprite so it can play animations.');
assert.match(initPhaserEffects, /buildPhaserAmmoEffects\(this\)/, 'Phaser should build ammo effect animations after preload.');
assert.match(initPhaserEffects, /phaserPlayerTurretSprite = this\.add\.image/, 'Phaser should create a player turret actor.');
assert.match(initPhaserEffects, /phaserPlayerSprite\.setVisible\(false\)/, 'Kenney actor trial should stay hidden until a full top-down scene migration is ready.');
assert.doesNotMatch(source, /kenney-actors-ready/, 'Kenney trial sprites should not hide DOM battle sprites yet.');

const initEnemyGalleryPhaser = bodyOf('initEnemyGalleryPhaser');
assert.match(initEnemyGalleryPhaser, /this\.load\.spritesheet\(`gallerySheet:\$\{key\}`/, 'Enemy Gallery should preload animated spritesheets instead of static SVG portraits.');
assert.match(initEnemyGalleryPhaser, /enemyGallerySprite = this\.add\.sprite/, 'Enemy Gallery preview actor should be a Phaser sprite so it can animate.');
assert.doesNotMatch(initEnemyGalleryPhaser, /this\.load\.svg\(`gallery:/, 'Enemy Gallery should not regress to static SVG gallery textures.');
assert.doesNotMatch(initEnemyGalleryPhaser, /enemyGallerySprite = this\.add\.image/, 'Enemy Gallery preview should not regress to a static image actor.');

const galleryAnimations = bodyOf('createEnemyGalleryAnimations');
assert.match(galleryAnimations, /Object\.entries\(enemyGalleryAnimationMap\)/, 'Enemy Gallery should define an animation for each gallery enemy id.');
assert.match(galleryAnimations, /generateFrameNumbers\(`gallerySheet:\$\{config\.sheet\}`/, 'Enemy Gallery animations should use the configured spritesheet frames.');
assert.match(galleryAnimations, /gallery-\$\{id\}-attack/, 'Enemy Gallery should define a one-shot attack animation for each enemy id.');
assert.match(galleryAnimations, /start: config\.attackStart, end: config\.attackEnd/, 'Enemy Gallery attack animations should use configured attack frame ranges.');
assert.match(source, /tank:\s*\{ sheet: "enemyTank"/, 'Basic tank gallery item should use the enemy tank spritesheet.');
assert.match(source, /tank:\s*\{[^}]*attackStart: 4, attackEnd: 7/, 'Basic tank gallery attack preview should use the enemy tank fire row.');
assert.match(source, /infantry:\s*\{ sheet: "regularInfantry"/, 'Regular soldier gallery item should use the regular infantry spritesheet.');
assert.match(source, /infantry:\s*\{[^}]*attackStart: 6, attackEnd: 11/, 'Regular soldier gallery attack preview should use its firing row.');
assert.match(source, /grenadier:\s*\{ sheet: "grenadier"/, 'Grenadier gallery item should use the grenadier spritesheet.');
assert.match(source, /boss:\s*\{ sheet: "bossTankDismantler"/, 'Boss gallery item should use the Tank Dismantler spritesheet.');
assert.match(source, /boss:\s*\{[^}]*attackStart: 6, attackEnd: 11/, 'Boss gallery attack preview should use the Tank Dismantler attack row.');
assert.match(source, /id="enemyGalleryAttackButton"/, 'Enemy Gallery should expose an Attack Preview button for children to trigger attacks.');

const renderEnemyGalleryPreview = bodyOf('renderEnemyGalleryPreview');
assert.match(renderEnemyGalleryPreview, /playEnemyGalleryAnimation\(item\)/, 'Enemy Gallery selections should play the selected unit animation.');
assert.match(renderEnemyGalleryPreview, /enemyGalleryFallback\.style\.display = "none"/, 'Enemy Gallery should hide the static fallback while an animated preview is available.');

const playEnemyGalleryAnimation = bodyOf('playEnemyGalleryAnimation');
assert.match(playEnemyGalleryAnimation, /enemyGallerySprite\.setTexture\(textureKey/, 'Enemy Gallery animation should switch the preview texture when kids click a different unit.');
assert.match(playEnemyGalleryAnimation, /startEnemyGalleryFrameLoop\(item, stateName, options\)/, 'Enemy Gallery animation should use the explicit frame loop so previews visibly advance.');
assert.match(playEnemyGalleryAnimation, /stateName === "attack" \? config\.attackStart : config\.start/, 'Enemy Gallery should start attack previews on the configured attack row.');

const galleryFrameLoop = bodyOf('startEnemyGalleryFrameLoop');
assert.match(galleryFrameLoop, /updateEnemyGallerySheetPreview\(item, stateName, range\)/, 'Enemy Gallery should update the visible spritesheet preview when an animation starts.');
assert.match(galleryFrameLoop, /window\.setInterval/, 'Enemy Gallery animation should explicitly advance frames over time.');
assert.match(galleryFrameLoop, /enemyGallerySprite\.setFrame\(frame\)/, 'Enemy Gallery animation should update the Phaser sprite frame directly.');
assert.match(galleryFrameLoop, /options\.onComplete\?\.\(\)/, 'Enemy Gallery one-shot attack previews should support completion callbacks.');

const sheetPreview = bodyOf('updateEnemyGallerySheetPreview');
assert.match(sheetPreview, /backgroundImage = `url\("\$\{sheet\.url\}"\)`/, 'Enemy Gallery should render the selected unit from its spritesheet image.');
assert.match(sheetPreview, /enemyGallerySheetPreview\.style\.animation = "none"/, 'Enemy Gallery visible spritesheet preview should be driven by the JS frame loop.');

const sheetFrameSetter = bodyOf('setEnemyGallerySheetFrame');
assert.match(sheetFrameSetter, /const column = frame % sheet\.columns/, 'Enemy Gallery visible spritesheet preview should calculate the frame column.');
assert.match(sheetFrameSetter, /const row = Math\.floor\(frame \/ sheet\.columns\)/, 'Enemy Gallery visible spritesheet preview should calculate the frame row.');
assert.match(sheetFrameSetter, /backgroundPosition = `\$\{-column \* sheet\.frameWidth\}px \$\{-row \* sheet\.frameHeight\}px`/, 'Enemy Gallery visible spritesheet preview should update background position for each frame.');
assert.match(source, /@keyframes enemy-gallery-sheet-play/, 'Enemy Gallery should define CSS keyframes for visible spritesheet playback.');
assert.match(source, /id="enemyGallerySheetPreview"/, 'Enemy Gallery should include a visible spritesheet preview layer over the Phaser backdrop.');

const galleryAttackPreview = bodyOf('playEnemyGalleryAttackPreview');
assert.match(galleryAttackPreview, /playEnemyGalleryAnimation\(item, "attack"/, 'Attack Preview button should play the selected unit attack animation.');
assert.match(galleryAttackPreview, /onComplete:/, 'Attack Preview should wait for the one-shot attack frame loop to finish.');
assert.match(galleryAttackPreview, /playEnemyGalleryAnimation\(item, "idle"\)/, 'Attack Preview should return the selected unit to idle after attacking.');
assert.match(source, /enemyGalleryAttackButton\.addEventListener\("click", playEnemyGalleryAttackPreview\)/, 'Enemy Gallery Attack Preview button should be wired to the attack preview handler.');

const updatePhaserActors = bodyOf('updatePhaserActors');
assert.match(updatePhaserActors, /fitPhaserSprite\(phaserPlayerTurretSprite/, 'Player turret should stay aligned with hull.');
assert.match(updatePhaserActors, /fitPhaserSprite\(phaserEnemyTurretSprite/, 'Enemy turret should stay aligned with hull.');
assert.match(updatePhaserActors, /updatePhaserPlayerTank\(\)/, 'Phaser player tank spritesheet should stay aligned with the DOM player slot.');
assert.match(updatePhaserActors, /setAngle\(phaserPlayerTextureReady \? 0/, 'Side-view player spritesheet should not inherit top-down actor rotation.');
assert.match(updatePhaserActors, /updatePhaserBossDismantler\(\)/, 'Phaser boss container should stay aligned with the DOM enemy slot.');
assert.match(updatePhaserActors, /updatePhaserRegularInfantry\(\)/, 'Regular soldier spritesheet should stay aligned with the DOM enemy slot.');
assert.match(updatePhaserActors, /updatePhaserRegularEnemyTank\(\)/, 'Regular enemy tank spritesheet should stay aligned with the DOM enemy slot.');
assert.match(updatePhaserActors, /updatePhaserGrenadier\(\)/, 'Grenadier spritesheet should stay aligned with the DOM enemy slot.');

const playerBuilder = bodyOf('buildPhaserPlayerTank');
const playerTextureReady = bodyOf('isPhaserPlayerTankTextureReady');
assert.match(playerTextureReady, /textures\?\.exists\(textureKey\)/, 'Player tank texture helper should verify that the selected spritesheet loaded.');
assert.match(source, /tank_is2:\s*"playerTankIs2Battle"/, 'Equipping Soviet: IS-2 should switch the Phaser player tank texture.');
assert.match(source, /tank_cromwell:\s*"playerTankCromwellBattle"/, 'Equipping Britain: Cromwell should switch the Phaser player tank texture.');
assert.match(source, /createPhaserPlayerTankAnimations\(scene, "playerTankIs2Battle", "player-tank-is2"\)/, 'IS-2 should have its own Phaser animation keys.');
assert.match(source, /createPhaserPlayerTankAnimations\(scene, "playerTankCromwellBattle", "player-tank-cromwell"\)/, 'Cromwell should have its own Phaser animation keys.');
const playerAnimationFactory = bodyOf('createPhaserPlayerTankAnimations');
assert.match(playerAnimationFactory, /`\$\{animationPrefix\}-\$\{stateName\}`/, 'Player tank animations should use the selected texture animation prefix.');
assert.match(playerAnimationFactory, /"idle", 0, 5/, 'Player idle animation should use row 1.');
assert.match(playerAnimationFactory, /"fire", 6, 11/, 'Player tank should define a fire animation.');
assert.match(playerAnimationFactory, /"fire", 6, 11/, 'Player fire animation should use row 2.');
assert.match(playerAnimationFactory, /"heavy-fire", 12, 17/, 'Player tank should define a heavy fire animation.');
assert.match(playerAnimationFactory, /"hit", 18, 23/, 'Player tank should define a hit animation.');
assert.match(playerAnimationFactory, /"hit", 18, 23/, 'Player hit animation should use the smoking row.');
assert.match(playerAnimationFactory, /"weak", 18, 23/, 'Player tank should define a weak animation.');
assert.match(playerAnimationFactory, /"weak", 18, 23/, 'Player weak animation should use row 4.');
assert.match(playerAnimationFactory, /"destroyed", 24, 29/, 'Player tank should define a destroyed animation.');
assert.match(playerAnimationFactory, /"destroyed", 24, 29/, 'Player destroyed animation should use row 5.');

const playerUpdater = bodyOf('updatePhaserPlayerTank');
assert.match(playerUpdater, /phaser-player-active/, 'DOM player fallback should hide only while the Phaser player tank is active.');
assert.match(playerUpdater, /setDisplaySize\(rect\.width \* 1\.18/, 'Player spritesheet should scale from the player DOM slot.');
assert.match(playerUpdater, /phaserPlayerKey !== textureKey[\s\S]*phaserPlayerSprite\.setTexture\(textureKey, 0\)/, 'Player spritesheet should change when a purchased tank skin is equipped.');

const playerState = bodyOf('getPlayerTankPhaserState');
assert.match(playerState, /return "destroyed"/, 'Player state should include destroyed.');
assert.match(playerState, /isPlayerTankWeak\(\)/, 'Player state should use the low-HP weak predicate.');
assert.match(playerState, /return "weak"/, 'Player state should include weak.');

const playerWeak = bodyOf('isPlayerTankWeak');
assert.match(playerWeak, /lives > 0 && lives <= 1/, 'Player weak state should only trigger when the tank has 1 HP left.');

const playerStatePlayer = bodyOf('playPhaserPlayerState');
assert.match(playerStatePlayer, /getEquippedPlayerTankAnimationPrefix\(\)/, 'Player animation helper should use the equipped tank animation prefix.');
assert.match(playerStatePlayer, /\$\{stateName\}/, 'Player animation helper should play named player tank states.');

const bossBuilder = bodyOf('buildPhaserBossDismantler');
assert.match(bossBuilder, /scene\.textures\.exists\("bossTankDismantler"\)/, 'Boss builder should verify that the spritesheet texture loaded.');
assert.match(bossBuilder, /bossTexture\.source\?\.\[0\]\?\.width \|\| 0\) >= 1344/, 'Boss builder should reject Phaser missing-texture placeholders.');
assert.match(bossBuilder, /if \(!phaserBossTextureReady\) return/, 'Boss builder should keep the DOM fallback when the spritesheet is unavailable.');
assert.match(bossBuilder, /key: "tank-dismantler-walk"/, 'Boss should define a walking spritesheet animation.');
assert.match(bossBuilder, /generateFrameNumbers\("bossTankDismantler", \{ start: 0, end: 5 \}\)/, 'Boss walk animation should use the first row of frames.');
assert.match(bossBuilder, /key: "tank-dismantler-attack"/, 'Boss should define an attack spritesheet animation.');
assert.match(bossBuilder, /generateFrameNumbers\("bossTankDismantler", \{ start: 6, end: 11 \}\)/, 'Boss attack animation should use the second row of frames.');
assert.match(bossBuilder, /scene\.add\.sprite\(0, 0, "bossTankDismantler", 0\)/, 'Boss should render as a Phaser spritesheet sprite.');
assert.match(bossBuilder, /setFlipX\(true\)/, 'Boss spritesheet should be mirrored to face the player from the enemy side.');

const bossUpdater = bodyOf('updatePhaserBossDismantler');
assert.match(bossUpdater, /currentEnemy\.id === "boss"/, 'Boss container should only appear for boss enemies.');
assert.match(bossUpdater, /phaserBossTextureReady && phaserBossDismantler/, 'Boss visibility should require a real loaded texture.');
assert.match(bossUpdater, /if \(phaserBossDismantler\) phaserBossDismantler\.setVisible\(active\)/, 'Boss container visibility should be lifecycle-driven.');
assert.match(bossUpdater, /enemyTank\.classList\.toggle\("phaser-boss-active", active\)/, 'DOM fallback sprite should hide only while the Phaser boss is active.');
assert.match(bossUpdater, /setDisplaySize\(size, size\)/, 'Boss spritesheet should be scaled to the battlefield slot.');
assert.match(bossUpdater, /phaserBossDismantler\.setFlipX\(true\)/, 'Boss orientation should stay mirrored after resize and position updates.');

const bossIdle = bodyOf('startPhaserBossIdle');
assert.match(bossIdle, /play\("tank-dismantler-walk", true\)/, 'Boss idle should play the walking spritesheet animation.');

const bossSlam = bodyOf('playPhaserBossSlam');
assert.match(bossSlam, /play\("tank-dismantler-attack", true\)/, 'Boss slam should play the attack spritesheet animation.');
assert.match(bossSlam, /animationcomplete-tank-dismantler-attack/, 'Boss should return to walking after the attack animation completes.');

const infantryBuilder = bodyOf('buildPhaserRegularInfantry');
assert.match(infantryBuilder, /scene\.textures\.exists\("regularInfantry"\)/, 'Regular soldier builder should verify that the spritesheet loaded.');
assert.match(infantryBuilder, /key: "regular-infantry-walk"/, 'Regular soldier should define a walk animation.');
assert.match(infantryBuilder, /generateFrameNumbers\("regularInfantry", \{ start: 0, end: 5 \}\)/, 'Regular soldier walk should use row 1 frames.');
assert.match(infantryBuilder, /key: "regular-infantry-fire"/, 'Regular soldier should define a firing animation.');
assert.match(infantryBuilder, /generateFrameNumbers\("regularInfantry", \{ start: 6, end: 11 \}\)/, 'Regular soldier fire should use row 2 frames.');
assert.match(infantryBuilder, /key: "regular-infantry-hit"/, 'Regular soldier should define a hit animation.');
assert.match(infantryBuilder, /setFlipX\(true\)/, 'Regular soldier source art faces right and must be flipped to face the player on the left.');

const infantryUpdater = bodyOf('updatePhaserRegularInfantry');
assert.match(infantryUpdater, /currentEnemy\.id === "infantry"/, 'Regular soldier spritesheet should only appear for stage 2 infantry.');
assert.match(infantryUpdater, /phaser-infantry-active/, 'DOM infantry fallback should hide only while the Phaser soldier is active.');
assert.match(infantryUpdater, /setDisplaySize\(rect\.width \* 1\.18, rect\.height \* 1\.42\)/, 'Regular soldier spritesheet should scale from the enemy DOM slot.');
assert.match(infantryUpdater, /phaserRegularInfantry\.setFlipX\(true\)/, 'Regular soldier orientation should stay flipped toward the left-side player after resize and updates.');

const infantryState = bodyOf('playPhaserRegularInfantryState');
assert.match(infantryState, /regular-infantry-\$\{stateName\}/, 'Regular soldier animation helper should play named states.');

const enemyTankBuilder = bodyOf('buildPhaserRegularEnemyTank');
assert.match(enemyTankBuilder, /scene\.textures\.exists\("regularEnemyTank"\)/, 'Regular enemy tank builder should verify that the spritesheet loaded.');
assert.match(enemyTankBuilder, /key: "regular-enemy-tank-idle"/, 'Regular enemy tank should define an idle animation.');
assert.match(enemyTankBuilder, /generateFrameNumbers\("regularEnemyTank", \{ start: 0, end: 5 \}\)/, 'Regular enemy tank idle should use row 1 frames.');
assert.match(enemyTankBuilder, /key: "regular-enemy-tank-fire"/, 'Regular enemy tank should define a fire animation.');
assert.match(enemyTankBuilder, /generateFrameNumbers\("regularEnemyTank", \{ start: 6, end: 11 \}\)/, 'Regular enemy tank fire should use row 2 frames.');
assert.match(enemyTankBuilder, /setFlipX\(true\)/, 'Regular enemy tank source art faces right and must be flipped to face the player on the left.');

const enemyTankUpdater = bodyOf('updatePhaserRegularEnemyTank');
assert.match(enemyTankUpdater, /currentEnemy\.id === "armor"/, 'Regular enemy tank spritesheet should appear for stage 3 armor enemy.');
assert.match(enemyTankUpdater, /phaser-enemy-tank-active/, 'DOM armor fallback should hide only while the Phaser tank is active.');
assert.match(enemyTankUpdater, /setDisplaySize\(rect\.width \* 1\.32, rect\.height \* 0\.92\)/, 'Regular enemy tank spritesheet should scale from the enemy DOM slot.');
assert.match(enemyTankUpdater, /phaserRegularEnemyTank\.setFlipX\(true\)/, 'Regular enemy tank orientation should stay flipped toward the left-side player after resize and updates.');

const enemyTankState = bodyOf('playPhaserRegularEnemyTankState');
assert.match(enemyTankState, /regular-enemy-tank-\$\{stateName\}/, 'Regular enemy tank animation helper should play named states.');

const grenadierBuilder = bodyOf('buildPhaserGrenadier');
assert.match(grenadierBuilder, /scene\.textures\.exists\("grenadier"\)/, 'Grenadier builder should verify that the spritesheet loaded.');
assert.match(grenadierBuilder, /key: "grenadier-walk"/, 'Grenadier should define a walk animation.');
assert.match(grenadierBuilder, /generateFrameNumbers\("grenadier", \{ start: 0, end: 5 \}\)/, 'Grenadier walk should use row 1 frames.');
assert.match(grenadierBuilder, /key: "grenadier-fire"/, 'Grenadier should define a throw/fire animation.');
assert.match(grenadierBuilder, /generateFrameNumbers\("grenadier", \{ start: 6, end: 11 \}\)/, 'Grenadier fire should use row 2 frames.');
assert.match(grenadierBuilder, /setFlipX\(true\)/, 'Grenadier source art faces right and must be flipped to face the player on the left.');

const grenadierUpdater = bodyOf('updatePhaserGrenadier');
assert.match(grenadierUpdater, /currentEnemy\.id === "grenadier"/, 'Grenadier spritesheet should appear for stage 4 grenadier enemy.');
assert.match(grenadierUpdater, /phaser-grenadier-active/, 'DOM grenadier fallback should hide only while the Phaser grenadier is active.');
assert.match(grenadierUpdater, /setDisplaySize\(rect\.width \* 1\.2, rect\.height \* 1\.42\)/, 'Grenadier spritesheet should scale from the enemy DOM slot.');
assert.match(grenadierUpdater, /phaserGrenadier\.setFlipX\(true\)/, 'Grenadier orientation should stay flipped toward the left-side player after resize and updates.');

const grenadierState = bodyOf('playPhaserGrenadierState');
assert.match(grenadierState, /grenadier-\$\{stateName\}/, 'Grenadier animation helper should play named states.');

const showDamage = bodyOf('showDamage');
assert.match(showDamage, /targetTank === enemyTank && currentEnemy\.id === "armor"/, 'Stage 3 regular tank should play hit animation when damaged.');
assert.match(showDamage, /targetTank === enemyTank && currentEnemy\.id === "grenadier"/, 'Stage 4 grenadier should play hit animation when damaged.');

const enemyFire = bodyOf('enemyFire');
assert.match(enemyFire, /playPhaserTargetingLine\(enemyTank, playerTank/, 'Enemy fire should show a Phaser targeting line before impact.');
assert.match(enemyFire, /if \(currentEnemy\.attackStyle === "melee"\)/, 'Melee enemies should route through melee strike attacks.');
assert.match(enemyFire, /const windupTime = currentEnemy\.id === "infantry" \|\| currentEnemy\.id === "grenadier" \? 260 : 160/, 'Ranged enemies should wind up before firing.');
assert.match(enemyFire, /getPhaserEnemyAttackTargets\(\)\.forEach/, 'Ranged wind-up should move the visible Phaser enemy actor.');
assert.match(enemyFire, /if \(currentEnemy\.id === "infantry"\) playPhaserRegularInfantryState\("fire"\)/, 'Regular soldier should play its firing animation when attacking.');
assert.match(enemyFire, /if \(currentEnemy\.id === "armor"\) playPhaserRegularEnemyTankState\("fire"\)/, 'Regular enemy tank should play its firing animation when attacking.');
assert.match(enemyFire, /if \(currentEnemy\.id === "grenadier"\) playPhaserGrenadierState\("fire"\)/, 'Grenadier should play its throw/fire animation when attacking.');

const enemyApproach = bodyOf('startPhaserEnemyApproach');
assert.match(enemyApproach, /currentEnemy\.attackStyle !== "melee"/, 'Only melee enemies should approach during reload.');
assert.match(enemyApproach, /getEnemyApproachDistance\(\)/, 'Phaser melee approach should use the shared actual-distance helper.');
const enemyApproachDistance = bodyOf('getEnemyApproachDistance');
assert.match(enemyApproachDistance, /currentEnemy\.approachDistance/, 'Melee approach should use per-enemy distance metadata.');
assert.match(enemyApproachDistance, /enemyPoint\.x - playerPoint\.x - desiredGap/, 'Phaser melee approach should derive distance from actual player/enemy positions.');
assert.match(source, /@keyframes boss-menace-approach[\s\S]*translateX\(clamp\(300px, 44vw, 760px\)\)/, 'Visible Boss reload approach should use viewport-relative distance.');
assert.match(source, /@keyframes boss-hammer-slam[\s\S]*0%[\s\S]*translateX\(clamp\(300px, 44vw, 760px\)\)/, 'Boss slam should start from its viewport-relative close reload position.');
assert.match(source, /@keyframes boss-attack-approach[\s\S]*translateX\(clamp\(300px, 44vw, 760px\)\)/, 'Boss attack should explicitly approach before the hammer swing.');
assert.match(source, /@keyframes melee-menace-approach[\s\S]*translateX\(clamp\(220px, 34vw, 620px\)\)/, 'Generic melee enemies should use viewport-relative approach distance.');
assert.match(source, /@keyframes melee-strike-attack[\s\S]*translateX\(clamp\(220px, 34vw, 620px\)\)/, 'Generic melee strike should start from close reload position.');

const enemyAttackTargets = bodyOf('getPhaserEnemyAttackTargets');
assert.match(enemyAttackTargets, /currentEnemy\.id === "infantry" && phaserRegularInfantry\?\.visible/, 'Regular soldier wind-up should target the visible infantry sprite.');
assert.match(enemyAttackTargets, /currentEnemy\.id === "armor" && phaserRegularEnemyTank\?\.visible/, 'Armored tank wind-up should target the visible tank sprite.');
assert.match(enemyAttackTargets, /currentEnemy\.id === "grenadier" && phaserGrenadier\?\.visible/, 'Grenadier wind-up should target the visible grenadier sprite.');

const meleeStrike = bodyOf('meleeStrikeAttack');
assert.match(meleeStrike, /tweenEnemyAttackToBase\(currentEnemy\.approachDistance/, 'Melee attack should close in using approach distance.');
assert.match(meleeStrike, /playPhaserImpact\(playerTank/, 'Melee attack should use Phaser hit feedback.');
assert.match(meleeStrike, /enemyTank\.classList\.add\("melee-strike"\)/, 'Generic melee attack should add a visible DOM strike class.');

const attackFromLane = bodyOf('attackFromLane');
assert.doesNotMatch(attackFromLane, /lane\.progress = 0;[\s\S]*laneEnemyAttack/, 'Lane soldiers should not teleport back before firing.');
assert.match(attackFromLane, /lane\.attacking = true/, 'Lane attacks should be guarded while the shot animation resolves.');

const startLaneAdvance = bodyOf('startLaneAdvance');
assert.match(startLaneAdvance, /if \(lane\.attacking\) return/, 'Lane advance ticks should not move soldiers during an attack animation.');

const laneEnemyAttack = bodyOf('laneEnemyAttack');
assert.match(laneEnemyAttack, /const windupTime = 220/, 'Lane soldiers should have a short wind-up before firing.');
assert.match(laneEnemyAttack, /playLaneProjectile\(lane\.element, playerTank/, 'Lane soldiers should fire from their current frontline position.');
assert.match(laneEnemyAttack, /lane\.progress = 0;[\s\S]*lane\.attacking = false;[\s\S]*syncLaneHud\(\)/, 'Lane soldiers should reset position only after the attack resolves.');

const shootLaneTargetFunction = bodyOf('shootLaneTarget');
assert.match(shootLaneTargetFunction, /ammo\?\.projectileSheet[\s\S]*playPhaserProjectile\(playerTank, lane\.element/, 'Multi-lane Arcane shots should use the Phaser projectile spritesheet path.');
assert.match(shootLaneTargetFunction, /projectileDuration = ammo\?\.projectileDuration \|\| 560/, 'Multi-lane projectile cleanup should respect slow special ammo travel time.');

const fireFunction = bodyOf('fire');
assert.match(fireFunction, /playPhaserPlayerState\(ammo\?\.id === "shell_he" \? "heavy-fire" : "fire", true\)/, 'Player fire should trigger the Phaser fire animation.');
assert.match(fireFunction, /effectSheet: ammo\?\.projectileSheet/, 'Player fire should pass ammo projectile spritesheet config to Phaser.');
assert.match(source, /const impactDelay = \(shotAmmo\?\.projectileDuration \|\| 900\) \+ \(shotAmmo\?\.projectileSheet \? 1050 : 0\)/, 'Multi-lane damage resolution should wait for slow Arcane projectile impact.');
assert.match(fireFunction, /const projectileDuration = ammo\?\.projectileDuration \|\| 560/, 'Special ammo should be able to slow down projectile travel for visibility.');

const gameOverFunction = bodyOf('showGameOver');
assert.match(gameOverFunction, /playPhaserPlayerState\("destroyed", true\)/, 'Game over should trigger the Phaser destroyed animation.');

const bossHammer = bodyOf('bossHammerAttack');
assert.match(bossHammer, /playPhaserBossSlam\(\)/, 'Boss hammer attack should trigger the assembled Phaser boss slam.');
assert.match(bossHammer, /const wasApproaching = enemyTank\.classList\.contains\("reloading"\) \|\| Boolean\(phaserEnemyReloadTween\)/, 'Boss hammer should detect an already-advanced reload pose.');
assert.match(bossHammer, /const approachDuration = wasApproaching \? 0 : 520/, 'Boss hammer should not jump back for a second approach when already close.');
assert.match(bossHammer, /const impactTime = approachDuration \+ swingWindup/, 'Boss hammer impact should happen after approach plus swing wind-up.');
assert.match(bossHammer, /const cleanupTime = impactTime \+ 600/, 'Boss hammer cleanup should wait for retreat after impact.');
assert.match(bossHammer, /stopPhaserEnemyApproach\(false\)/, 'Boss hammer should stop stale approach tweens without resetting position.');
assert.match(bossHammer, /tweenEnemyAttackToBase\(getEnemyApproachDistance\(\), \{ angle: -9, inDuration: Math\.max\(160, impactTime\), outDuration: 520 \}\)/, 'Boss Phaser movement should continue from the current position to impact and retreat afterward.');
assert.match(bossHammer, /enemyTank\.classList\.add\("boss-attack-approach"\)/, 'Boss DOM attack should visibly approach before swinging.');
assert.match(bossHammer, /enemyTank\.classList\.remove\("boss-attack-approach"\);\s*enemyTank\.classList\.add\("boss-slam"\)/, 'Boss DOM attack should switch from approach to slam.');
assert.match(bossHammer, /\}, impactTime\)/, 'Boss damage should land at the scripted axe impact timing.');
assert.match(source, /\.tank\.enemy\.boss-slam \{\s*animation: boss-hammer-slam 1120ms/, 'Boss DOM slam animation duration should match the post-approach swing window.');
assert.match(source, /\.tank\.enemy\.boss-attack-approach \{\s*animation: boss-attack-approach 520ms/, 'Boss DOM approach duration should match the scripted approach phase.');

assert.match(source, /playPhaserDestruction\(enemyTank, \{ heavy: currentEnemy\.id === "boss", direction: -1 \}\)/, 'Enemy death should use Phaser destruction.');
assert.match(source, /playPhaserDestruction\(playerTank, \{ heavy: true, direction: 1 \}\)/, 'Player defeat should use Phaser destruction.');
assert.match(source, /\.tank\.player\.destroyed\.fragmented \.tank-sprite/, 'Fragmented player tank styling should override static destroyed sprite styling.');

console.log('phaser VFX regression tests passed');
