const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');

function bodyOf(functionName) {
  const start = source.indexOf(`function ${functionName}`);
  assert.notStrictEqual(start, -1, `Missing function ${functionName}`);
  const parametersEnd = source.indexOf(') {', start);
  assert.notStrictEqual(parametersEnd, -1, `Could not find body start for function ${functionName}`);
  const braceStart = source.indexOf('{', parametersEnd);
  let depth = 0;
  for (let index = braceStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    if (depth === 0) return source.slice(braceStart + 1, index);
  }
  throw new Error(`Could not parse function ${functionName}`);
}

const cameraKick = bodyOf('kickPhaserCamera');
assert.match(cameraKick, /camera\.shake\(/, 'Phaser camera shake should be used for impact feedback.');
assert.match(cameraKick, /camera\.flash\(/, 'Phaser camera flash should be used for explosion feedback.');

const shockwave = bodyOf('addPhaserShockwave');
assert.match(shockwave, /setStrokeStyle/, 'Explosion shockwave should be a stroked Phaser ring.');
assert.match(shockwave, /scale: heavy \? 6\.2 : 4\.2/, 'Shockwave should expand dramatically.');

const smoke = bodyOf('addPhaserSmoke');
assert.match(smoke, /puffCount = heavy \? 13 : 8/, 'Explosion should create multiple smoke puffs.');
assert.match(smoke, /scene\.add\.circle/, 'Smoke should be generated by Phaser primitives.');

const sparks = bodyOf('addPhaserSparks');
assert.match(sparks, /sparkCount = heavy \? 34 : 18/, 'Explosion should create many sparks.');
assert.match(sparks, /scene\.add\.rectangle/, 'Sparks should use Phaser primitives.');

const explosion = bodyOf('playPhaserExplosion');
assert.match(explosion, /kickPhaserCamera\(heavy \? "heavy" : "normal"\)/, 'Explosion should kick the Phaser camera.');
assert.match(explosion, /addPhaserShockwave\(/, 'Explosion should include shockwave.');
assert.match(explosion, /addPhaserSparks\(/, 'Explosion should include sparks.');
assert.match(explosion, /addPhaserSmoke\(/, 'Explosion should include smoke.');
assert.doesNotMatch(explosion, /const smoke = scene\.add\.circle/, 'Explosion should not regress to a single smoke circle.');

const debris = bodyOf('addPhaserArmorDebris');
assert.match(debris, /chunkCount = heavy \? 42 : 26/, 'Tank destruction should create many armor chunks.');
assert.match(debris, /scene\.add\.rectangle/, 'Tank destruction should use Phaser debris primitives.');

const destruction = bodyOf('playPhaserDestruction');
assert.match(destruction, /targetEl\.classList\.add\("fragmented"\)/, 'Tank body should fade out when Phaser destruction starts.');
assert.match(destruction, /addPhaserArmorDebris\(/, 'Tank destruction should throw armor debris.');
assert.match(destruction, /addPhaserSparks\(/, 'Tank destruction should include sparks.');
assert.match(destruction, /addPhaserSmoke\(/, 'Tank destruction should include smoke.');

const muzzleFlash = bodyOf('addPhaserMuzzleFlash');
assert.match(muzzleFlash, /scene\.add\.star/, 'Projectile fire should use a Phaser muzzle flash star.');
assert.match(muzzleFlash, /scene\.add\.circle/, 'Projectile fire should use a Phaser muzzle bloom.');

const projectileTrail = bodyOf('addPhaserProjectileTrail');
assert.match(projectileTrail, /trailCount = 8/, 'Projectile should leave multiple Phaser trail puffs.');
assert.match(projectileTrail, /scene\.add\.circle/, 'Projectile trail should use Phaser primitives.');

const impactGlint = bodyOf('addPhaserImpactGlint');
assert.match(impactGlint, /setStrokeStyle/, 'Projectile impact should create a stroked Phaser glint.');

const targetingLine = bodyOf('playPhaserTargetingLine');
assert.match(targetingLine, /phaserEffects\.add\.line/, 'Enemy attacks should use a Phaser targeting line.');
assert.match(targetingLine, /setLineWidth/, 'Targeting line should have visible thickness.');
assert.match(targetingLine, /phaserEffects\.add\.circle/, 'Targeting should include a Phaser impact reticle.');

const projectile = bodyOf('playPhaserProjectile');
assert.match(projectile, /addPhaserMuzzleFlash\(/, 'Projectile should trigger muzzle flash.');
assert.match(projectile, /addPhaserProjectileTrail\(/, 'Projectile should trigger trail effects.');
assert.match(projectile, /addPhaserImpactGlint\(/, 'Projectile should trigger impact glint.');

const initPhaserEffects = bodyOf('initPhaserEffects');
assert.match(initPhaserEffects, /this\.load\.image\("kenney:playerHull"/, 'Phaser should preload Kenney player hull PNG.');
assert.match(initPhaserEffects, /this\.load\.image\("kenney:playerTurret"/, 'Phaser should preload Kenney player turret PNG.');
assert.match(initPhaserEffects, /this\.load\.image\("kenney:enemyHull"/, 'Phaser should preload Kenney enemy hull PNG.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("playerTankBattle"/, 'Phaser should preload the player tank battle spritesheet.');
assert.match(initPhaserEffects, /frameWidth: 224[\s\S]*frameHeight: 144/, 'Player tank spritesheet should use fixed frame dimensions.');
assert.match(initPhaserEffects, /this\.load\.spritesheet\("bossTankDismantler"/, 'Phaser should preload the Tank Dismantler boss spritesheet.');
assert.match(initPhaserEffects, /frameWidth: 224/, 'Tank Dismantler spritesheet should use fixed frame width.');
assert.match(initPhaserEffects, /frameHeight: 224/, 'Tank Dismantler spritesheet should use fixed frame height.');
assert.match(initPhaserEffects, /phaserPlayerSprite = this\.add\.sprite/, 'Player actor should be a Phaser sprite so it can play animations.');
assert.match(initPhaserEffects, /phaserPlayerTurretSprite = this\.add\.image/, 'Phaser should create a player turret actor.');
assert.match(initPhaserEffects, /phaserPlayerSprite\.setVisible\(false\)/, 'Kenney actor trial should stay hidden until a full top-down scene migration is ready.');
assert.doesNotMatch(source, /kenney-actors-ready/, 'Kenney trial sprites should not hide DOM battle sprites yet.');

const updatePhaserActors = bodyOf('updatePhaserActors');
assert.match(updatePhaserActors, /fitPhaserSprite\(phaserPlayerTurretSprite/, 'Player turret should stay aligned with hull.');
assert.match(updatePhaserActors, /fitPhaserSprite\(phaserEnemyTurretSprite/, 'Enemy turret should stay aligned with hull.');
assert.match(updatePhaserActors, /updatePhaserPlayerTank\(\)/, 'Phaser player tank spritesheet should stay aligned with the DOM player slot.');
assert.match(updatePhaserActors, /setAngle\(phaserPlayerTextureReady \? 0/, 'Side-view player spritesheet should not inherit top-down actor rotation.');
assert.match(updatePhaserActors, /updatePhaserBossDismantler\(\)/, 'Phaser boss container should stay aligned with the DOM enemy slot.');

const playerBuilder = bodyOf('buildPhaserPlayerTank');
assert.match(playerBuilder, /scene\.textures\.exists\("playerTankBattle"\)/, 'Player tank builder should verify that the spritesheet loaded.');
assert.match(playerBuilder, /key: "player-tank-idle"/, 'Player tank should define an idle animation.');
assert.match(playerBuilder, /start: 0, end: 3/, 'Player idle animation should use row 1.');
assert.match(playerBuilder, /key: "player-tank-fire"/, 'Player tank should define a fire animation.');
assert.match(playerBuilder, /start: 4, end: 7/, 'Player fire animation should use row 2.');
assert.match(playerBuilder, /key: "player-tank-hit"/, 'Player tank should define a hit animation.');
assert.match(playerBuilder, /start: 8, end: 11/, 'Player hit animation should use row 3.');
assert.match(playerBuilder, /key: "player-tank-weak"/, 'Player tank should define a weak animation.');
assert.match(playerBuilder, /start: 12, end: 15/, 'Player weak animation should use row 4.');
assert.match(playerBuilder, /key: "player-tank-destroyed"/, 'Player tank should define a destroyed animation.');
assert.match(playerBuilder, /start: 16, end: 19/, 'Player destroyed animation should use row 5.');

const playerUpdater = bodyOf('updatePhaserPlayerTank');
assert.match(playerUpdater, /phaser-player-active/, 'DOM player fallback should hide only while the Phaser player tank is active.');
assert.match(playerUpdater, /setDisplaySize\(rect\.width \* 1\.08/, 'Player spritesheet should scale from the player DOM slot.');

const playerState = bodyOf('getPlayerTankPhaserState');
assert.match(playerState, /return "destroyed"/, 'Player state should include destroyed.');
assert.match(playerState, /return "weak"/, 'Player state should include weak.');

const playerStatePlayer = bodyOf('playPhaserPlayerState');
assert.match(playerStatePlayer, /player-tank-\$\{stateName\}/, 'Player animation helper should play named player tank states.');

const bossBuilder = bodyOf('buildPhaserBossDismantler');
assert.match(bossBuilder, /scene\.textures\.exists\("bossTankDismantler"\)/, 'Boss builder should verify that the spritesheet texture loaded.');
assert.match(bossBuilder, /bossTexture\.source\?\.\[0\]\?\.width \|\| 0\) >= 1344/, 'Boss builder should reject Phaser missing-texture placeholders.');
assert.match(bossBuilder, /if \(!phaserBossTextureReady\) return/, 'Boss builder should keep the DOM fallback when the spritesheet is unavailable.');
assert.match(bossBuilder, /key: "tank-dismantler-walk"/, 'Boss should define a walking spritesheet animation.');
assert.match(bossBuilder, /generateFrameNumbers\("bossTankDismantler", \{ start: 0, end: 5 \}\)/, 'Boss walk animation should use the first row of frames.');
assert.match(bossBuilder, /key: "tank-dismantler-attack"/, 'Boss should define an attack spritesheet animation.');
assert.match(bossBuilder, /generateFrameNumbers\("bossTankDismantler", \{ start: 6, end: 11 \}\)/, 'Boss attack animation should use the second row of frames.');
assert.match(bossBuilder, /scene\.add\.sprite\(0, 0, "bossTankDismantler", 0\)/, 'Boss should render as a Phaser spritesheet sprite.');

const bossUpdater = bodyOf('updatePhaserBossDismantler');
assert.match(bossUpdater, /currentEnemy\.id === "boss"/, 'Boss container should only appear for boss enemies.');
assert.match(bossUpdater, /phaserBossTextureReady && phaserBossDismantler/, 'Boss visibility should require a real loaded texture.');
assert.match(bossUpdater, /if \(phaserBossDismantler\) phaserBossDismantler\.setVisible\(active\)/, 'Boss container visibility should be lifecycle-driven.');
assert.match(bossUpdater, /enemyTank\.classList\.toggle\("phaser-boss-active", active\)/, 'DOM fallback sprite should hide only while the Phaser boss is active.');
assert.match(bossUpdater, /setDisplaySize\(size, size\)/, 'Boss spritesheet should be scaled to the battlefield slot.');

const bossIdle = bodyOf('startPhaserBossIdle');
assert.match(bossIdle, /play\("tank-dismantler-walk", true\)/, 'Boss idle should play the walking spritesheet animation.');

const bossSlam = bodyOf('playPhaserBossSlam');
assert.match(bossSlam, /play\("tank-dismantler-attack", true\)/, 'Boss slam should play the attack spritesheet animation.');
assert.match(bossSlam, /animationcomplete-tank-dismantler-attack/, 'Boss should return to walking after the attack animation completes.');

const enemyFire = bodyOf('enemyFire');
assert.match(enemyFire, /playPhaserTargetingLine\(enemyTank, playerTank/, 'Enemy fire should show a Phaser targeting line before impact.');
assert.match(enemyFire, /if \(currentEnemy\.attackStyle === "melee"\)/, 'Melee enemies should route through melee strike attacks.');

const enemyApproach = bodyOf('startPhaserEnemyApproach');
assert.match(enemyApproach, /currentEnemy\.attackStyle !== "melee"/, 'Only melee enemies should approach during reload.');
assert.match(enemyApproach, /currentEnemy\.approachDistance/, 'Melee approach should use per-enemy distance metadata.');
assert.match(enemyApproach, /enemyPoint\.x - playerPoint\.x - desiredGap/, 'Phaser melee approach should derive distance from actual player/enemy positions.');
assert.match(source, /@keyframes boss-menace-approach[\s\S]*translateX\(clamp\(300px, 44vw, 760px\)\)/, 'Visible Boss reload approach should use viewport-relative distance.');
assert.match(source, /@keyframes boss-hammer-slam[\s\S]*0%[\s\S]*translateX\(clamp\(300px, 44vw, 760px\)\)/, 'Boss slam should start from its viewport-relative close reload position.');
assert.match(source, /@keyframes melee-menace-approach[\s\S]*translateX\(clamp\(220px, 34vw, 620px\)\)/, 'Generic melee enemies should use viewport-relative approach distance.');
assert.match(source, /@keyframes melee-strike-attack[\s\S]*translateX\(clamp\(220px, 34vw, 620px\)\)/, 'Generic melee strike should start from close reload position.');

const meleeStrike = bodyOf('meleeStrikeAttack');
assert.match(meleeStrike, /tweenEnemyAttackToBase\(currentEnemy\.approachDistance/, 'Melee attack should close in using approach distance.');
assert.match(meleeStrike, /playPhaserImpact\(playerTank/, 'Melee attack should use Phaser hit feedback.');
assert.match(meleeStrike, /enemyTank\.classList\.add\("melee-strike"\)/, 'Generic melee attack should add a visible DOM strike class.');

const fireFunction = bodyOf('fire');
assert.match(fireFunction, /playPhaserPlayerState\("fire", true\)/, 'Player fire should trigger the Phaser fire animation.');

const gameOverFunction = bodyOf('showGameOver');
assert.match(gameOverFunction, /playPhaserPlayerState\("destroyed", true\)/, 'Game over should trigger the Phaser destroyed animation.');

const bossHammer = bodyOf('bossHammerAttack');
assert.match(bossHammer, /playPhaserBossSlam\(\)/, 'Boss hammer attack should trigger the assembled Phaser boss slam.');

assert.match(source, /playPhaserDestruction\(enemyTank, \{ heavy: currentEnemy\.id === "boss", direction: -1 \}\)/, 'Enemy death should use Phaser destruction.');
assert.match(source, /playPhaserDestruction\(playerTank, \{ heavy: true, direction: 1 \}\)/, 'Player defeat should use Phaser destruction.');
assert.match(source, /\.tank\.player\.destroyed\.fragmented \.tank-sprite/, 'Fragmented player tank styling should override static destroyed sprite styling.');

console.log('phaser VFX regression tests passed');
